version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/exam_scheduling
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exam_scheduling
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build:
      context: ../frontendtwaaos
      args:
        - REACT_APP_API_URL=http://app:5000
    container_name: react_frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
